### ISSUE TITLE
Wallet Promotion bug report

### ISSUE THREAD

**Issue by justinberg** [nowgoin/public_issue_tracker#11]
- [x] Insufficient funds go away when the promotion. We decided that they need to have enough funds to use the promotion. We just need to show that they have a promotion. 
- [x] Show in Wallet history. Show when a promotion is redeemed also. 
![image](https://user-images.githubusercontent.com/4731880/95120571-9ff69b00-0702-11eb-88ef-669059f945b0.png)
Feedback: https://www.loom.com/share/62046a33065b4377b66034d950f59e31

- [x] PSTA MOD Free to show a Zero wallet transaction. This would show in history also.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2124h)

**Comment by sumitsimform** [comment]
@justinberg : this is the start of full history section : -https://www.loom.com/share/19637809aaa844cb8cc8308455f1ad69
give me feedback that i am going in right direction .

**Comment by sumitsimform** [comment]
@webdeveloper001 @justinberg  : please explain me the flow of promo code apply.

**Comment by sumitsimform** [comment]
@justinberg  @daniellewallace1  : please explain me in this. what is not working here.

**Comment by daniellewallace1** [comment]
@sumitsimform We need to show the fares for everything. Example show redemption of promotional fare, promotions (coupons), and promotions fare (a service with has a limit of 100 trips per month) show each one of the redemptions.

**Comment by sumitsimform** [comment]
@webdeveloper001 : please check this pr 
https://github.com/nowgoin/goin-payment-v3/pull/33

**Comment by justinberg** [comment]
Not sure how to test this one. I think we just move to prod as it should be a low impact change. @cole-borroar

**Comment by justinberg** [comment]
@sumitsimform Please see this video. I've taken about 100 trips since June but full history is only showing from June 4th. 

https://www.loom.com/share/e66006bc3835464fb79b6c6ff98e9ad5

**Comment by sumitsimform** [comment]
@justinberg : in the new application, i am unable to proceed further after this page : - http://files.simformsolutions.com.s3.amazonaws.com/simformscreen/GOIN_2021-01-25_17-20-08.png
So i am unable to debug this issue.

**Comment by justinberg** [comment]
Waiting on #1137
