### ISSUE TITLE
Wallet history: Add initiated by Name, Team member or Rider

### ISSUE THREAD

**Issue by justinberg** [nowgoin/public_issue_tracker#7]
- [ ] Show a record in Full History when a trip is used that has a promotion. 

This only works sometimes. it would be nice to see who for all of the debts and credits and funding of the wallet. 

But the user or rider that funds the wallet through the web or rider app should show here also or who requested the ride the user or the rider.

![image](https://user-images.githubusercontent.com/4731880/80031544-b4214580-849e-11ea-95c8-37c389e73c7c.png)

I have added $15.00 to the account and it still does not reflect the initiated by in the wallet.

**Comment by justinberg** [comment]
@cole-borroar Status?

**Comment by sumitsimform** [comment]
@justinberg : it is in progress.

**Comment by sumitsimform** [comment]
@daniellewallace1  : any feedback on this.

**Comment by sumitsimform** [comment]
It's reflecting with the new transactions only.

**Comment by sumitsimform** [comment]
@justinberg  : what i need to change in this.

**Comment by justinberg** [comment]
This is done.
